// Generated by `wrangler types` (`mise run //apps/web:types`). Regenerate
// after editing wrangler.jsonc rather than hand-editing this file.
// The app has no bindings today, so this is a placeholder until the first
// real `wrangler types` run fills it in.
interface Env {}
